# Generated by Django 4.2.2 on 2023-06-08 11:11

from decimal import Decimal

from django.db import migrations
from wallets.rsa import generate_rsa


def create_sender_and_recipient(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Wallet = apps.get_model("wallets", "Wallet")

    sender_user = User.objects.create_user(username="sender", password="sender")
    recipient_user = User.objects.create_user(
        username="recipient", password="recipient"
    )

    rsa1 = generate_rsa()
    Wallet.objects.create(
        user=sender_user,
        balance=Decimal("1000.00"),
        private_key=rsa1[0],
        public_key=rsa1[1],
    )

    rsa2 = generate_rsa()
    Wallet.objects.create(
        user=recipient_user,
        balance=Decimal("1000.00"),
        private_key=rsa2[0],
        public_key=rsa2[1],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_wallet_private_key_wallet_public_key"),
    ]

    operations = [
        migrations.RunPython(create_sender_and_recipient, migrations.RunPython.noop),
    ]
