# Generated by Django 4.2.2 on 2023-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="proof",
            field=models.CharField(max_length=256),
        ),
    ]
