# Generated by Django 4.2.2 on 2023-06-08 11:09

from datetime import datetime
from decimal import Decimal

from django.db import migrations


def create_initial_block(apps, schema_editor):
    Block = apps.get_model("blockchain", "Block")
    Transaction = apps.get_model("blockchain", "Transaction")
    Wallet = apps.get_model("wallets", "Wallet")

    sender = Wallet.objects.get(user__username="sender")
    recipient = Wallet.objects.get(user__username="recipient")

    initial_block = Block.objects.create(
        previous_hash=b"first_block",
        security_hashes=[b"first_block"],
        proof="0001",
        timestamp=datetime(2023, 6, 4, 12, 47, 35, 763550),
    )
    Transaction.objects.create(
        sender=sender,
        recipient=recipient,
        amount=Decimal("1000.00"),
        block=initial_block,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0002_alter_block_proof"),
        ("wallets", "0003_create_initial_sender_and_recipient"),
    ]

    operations = [
        migrations.RunPython(create_initial_block, migrations.RunPython.noop),
    ]
