# Generated by Django 4.2.2 on 2023-06-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0003_create_initial_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="previous_hash",
            field=models.BinaryField(unique=True),
        ),
    ]
