# Generated by Django 4.2.2 on 2023-06-11 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0005_alter_block_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(default=dict), size=None
                    ),
                ),
                ("difficulty", models.CharField(max_length=32)),
            ],
        ),
    ]
