# Generated by Django 4.2.2 on 2023-06-11 15:18

from django.db import migrations

from blockchain.dtos import BlockDto, TransactionDto


def setup_blockchain(apps, schema_editor):
    Chain = apps.get_model("blockchain", "Chain")
    Block = apps.get_model("blockchain", "Block")

    initial_block = Block.objects.get(previous_hash=b"first_block")
    dto = BlockDto(
        previous_hash=initial_block.previous_hash,
        timestamp=initial_block.timestamp,
        security_hashes=initial_block.security_hashes,
        proof=initial_block.proof,
        transactions=[
            TransactionDto.from_transaction_object(transaction)
            for transaction in initial_block.transactions.select_related(
                "sender", "recipient"
            )
        ],
    )
    Chain.objects.create(blocks=[dto.to_dict()], difficulty="0001")


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0006_chain"),
    ]

    operations = [
        migrations.RunPython(setup_blockchain, migrations.RunPython.noop),
    ]
