name: Test backend
on: 
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install poetry
        run: pip install poetry
      - name: Setup project
        run: poetry config virtualenvs.in-project true --local && poetry install -n --no-root
      - name: Run test services
        run: docker-compose up -d db
      - name: Format
        run: make -C blockchain format_all
      - name: Test
        run: make -C blockchain test
